import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Button from '../components/Button'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>mythinks 🚀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
        <section className={styles.section}>
        <img className={styles.img} src='/Thinks.png' alt='Logo' />
          <h1 className={styles.title}>
            Thinks
          </h1>
          <h2>
            Talk about anything
          </h2>
          <div className={styles.button}>
            <Button>Login with GitHub</Button>
          </div>
          </section>
        </main>
      </div>
  )
}
